export const EVENTS = {
  CLICK_SEE_JOB: 'CLICK_SEE_JOB',
  CLICK_APPLY_FILTERS: 'CLICK_APPLY_FILTERS',
  CLICK_COMPANIES_TO_AVOID_LINK: 'CLICK_COMPANIES_TO_AVOID_LINK',
  CLICK_MARK_JOB_AS_EXPIRED: 'CLICK_MARK_JOB_AS_EXPIRED',
};